// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnoozxifgnsnvscxlqms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indub296eGlmZ25zbnZzY3hscW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMDIzOTksImV4cCI6MjA4Nzc3ODM5OX0.re1l5FtLogfxTy-ZdvJ0PmsY2SQljr0Z64PuYpck2pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});